### ISSUE TITLE
Class 'BootHelp' not found

### ISSUE THREAD

**Issue by cijagani** [cobisja/boothelp#1]
hi, followed all that steps, but i am getting Fatal error: Class 'BootHelp' not found

**Comment by cobisja** [comment]
Hi my friend,

Please send me your sample code to check it.

Thanks in advance,

Cobis

**Comment by cijagani** [comment]
here is index page that i can see.
![index_page](https://cloud.githubusercontent.com/assets/3807730/9000646/696e9f98-3768-11e5-82da-b4b163099c39.PNG)

then i created demo.php file in project root 
![error](https://cloud.githubusercontent.com/assets/3807730/9000652/859a7bf6-3768-11e5-9327-1d3cc4610c6c.PNG)

here is a link of source code
https://drive.google.com/file/d/0ByBdB_-hy3gMZW1QczBoYjYycVk/view?usp=sharing

please check,  what is missing.

thanks in advance.

**Comment by cobisja** [comment]
Hello my friend,

Sorry, I'm late to giving you an answer for your issue.

I was looking for your code and I found some problems:
1. The *require *sentence has an error. The correct sentence should be:

_require 'vendor/autoload.php';_
You have to note that your script is in the same folder where _'vendor'_
folder is located, so you have to use a 'relative path'. It implies that
you have to omit the first slash.
1. You don't have to require the file\* boothelp.php_, because the autoload
   already loaded it in memory for you. So you have to delete the *require
   'boothelp.php'_.
2. Your _use sentence_ is incomplete. Remember you have to use the full
   qualiffied name for a class. In this case you have tu use:

_use cobisja\BootHelp\BootHelp;_
4. At this point you code should work, however you will not see the _modal
component_, or any other, because you have to keep in mind that _BootHelp_ _is
just about for_
_generating html code_
_according Bootsrap specifications, nothing else_, and it should be doing
that. To see the whole BootHelp components you have to load the following:
- jQuery javascript file.
- Twitter bootstrap css files.
- Twitter bootstrap font files.
- Twitter bootstrap javascript files

Check the _Boothelp's index.php_. Look at the _head section_ and also look
at the end of the file to see how to load the files mentioned above.

Keep in touch,

Cobis

2015-07-30 23:46 GMT-04:30 Jagani Chirag notifications@github.com:

**Comment by cijagani** [comment]
hello Cobis,

thanks for you reply and suggestions.
i would like to inform you that i resolve this error "Class 'BootHelp' not found"  

major problem was that i used BootHelp instead of  cobisja\BootHelp\BootHelp;so

use BootHelp     --- is worng
use cobisja\BootHelp\BootHelp; --- is right.

and then i embedded jquey and bootstrap files in the page. 
now it is working fine.

thanks for your guidance. 
chirag jagani

**Comment by cobisja** [comment]
It's been my pleasure.

By the way,  if you are interested in a full version of BootHelp, you can
visit:

http://codecanyon.net/item/boothelp-php-helpers-for-bootstrap/11636009

That version has support for tables and carousels. Check it out!!!

Best regards,

Cobis
